spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
  datasource:
    username: my
    password: ticket
    url: 'jdbc:mysql://localhost:4306/myticket'
server:
  servlet:
    context-path: '/api/v1'
token:
  secret: "RATP loves Laravel more than Symfony"
  validForHours: 24